[variables]
NIXPACKS_NODE_VERSION = "22"

[phases.setup]
nixpkgsArchive = "3e2cf88148e732abc1d259286123e06a9d8c964a"

[phases.install]
cmds = [
  "npm install --prefix backend",
  "npm install --prefix frontend"
]

[phases.build]
cmds = [
  "cd backend && npx prisma generate",
  "cd frontend && npm run build"
]

[start]
cmd = "node backend/src/index.js"
